development:
  # adapter: sqlite3
  # database: db/development.sqlite3
  # pool: 5
  # timeout: 10000
  adapter: postgresql
  database: fourthmeal_development
  host: localhost
  pool: 25

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: foodfight_production
  pool: 5
  username: foodfight
  password:
