development:
  adapter: postgresql
  database: foodfight_development
  host: localhost

test:
  adapter: postgresql
  database: foodfight_test
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: foodfight_production
  pool: 5
  username: foodfight
  password:
